import Home from "@/assets/icons/home.svg";
import Truck from "@/assets/icons/freight.svg";
import Support from "@/assets/icons/support.svg";
import Warning from "@/assets/icons/warning.svg";
import Logout from "@/assets/icons/logout.svg";
import TruckDriver from "../assets/icons/truck-driver.svg";
import Finance from "../assets/icons/finance.svg";
import Config from "../assets/icons/config.svg";
import Clients from "../assets/icons/clients.svg";
import Help from "@/assets/icons/help.svg";
import Check from "@/assets/icons/check.svg";
import Eye from "@/assets/icons/eye.svg";
import HideEye from "@/assets/icons/hideEye.svg";
import ArrowRight from "@/assets/icons/arrowRight.svg";
import ArrowDown from "@/assets/icons/arrowDown.svg";
import Magnifier from "@/assets/icons/magnifier.svg";
import ShippingBox from "@/assets/icons/shippingBox.svg";
import ShipmentCheck from "@/assets/icons/shipmentCheck.svg";
import MagnifyingGlass from "@/assets/icons/magnifyingGlass.svg";
import VerticalDots from "@/assets/icons/verticalDots.svg";
import LogoWhatsapp from "@/assets/icons/logoWhatsapp.svg";
import Separator from "@/assets/icons/separator.svg";
import Pencil from "@/assets/icons/pencil.svg";
import PaperClip from "@/assets/icons/paperClip.svg";
import Danger from "@/assets/icons/danger.svg";
import WhatsApp from "@/assets/icons/whatsapp.svg";
import TrueIcon from "@/assets/icons/trueIcon.svg";
import FalseIcon from "@/assets/icons/falseIcon.svg";
import CheckBox from "@/assets/icons/checkbox-check.svg";
import CheckBoxUncheck from "@/assets/icons/checkbox-uncheck.svg";
import PickupOrder from "@/assets/icons/pickupOrder.svg";
import CarryingLoad from "@/assets/icons/carryingLoad.svg";
import InRoute from "@/assets/icons/inRoute.svg";
import ArrivalAtDestination from "@/assets/icons/arrivalAtDestination.svg";
import SendingReceipts from "@/assets/icons/sendingReceipts.svg";
import Balance from "@/assets/icons/balance.svg";
import Back from "@/assets/icons/back.svg";
import PencilSolid from "@/assets/icons/pencilSolid.svg";
import Download from "@/assets/icons/download.svg";
import Fretador from "@/assets/icons/fretador.svg";
import AttachmentDark from "@/assets/icons/teenyicons_doc-outline.svg";
import AttachmentLight from "@/assets/icons/teenyicons_doc-outline (1).svg";
import Close from "@/assets/icons/close-outline.svg";
import { FaCalculator } from "react-icons/fa";
import Play from "@/assets/icons/play.svg"

export const HomeIcon = Home;
export const TruckIcon = Truck;
export const PersonAddIcon = TruckDriver;
export const ClientsBook = Clients;
export const MagniFyingGlassIcon = MagnifyingGlass;
export const WarningIcon = Warning;
export const FinanceIcon = Finance;
export const SettingsIcon = Config;
export const SupportIcon = Support;
export const HelpIcon = Help;
export const LogoutIcon = Logout;
export const CheckIcon = Check;
export const EyeIcon = Eye;
export const HideEyeIcon = HideEye;
export const ArrowRightIcon = ArrowRight;
export const ArrowDownIcon = ArrowDown;
export const MagnifierIcon = Magnifier;
export const ShippingBoxIcon = ShippingBox;
export const ShipmentCheckIcon = ShipmentCheck;
export const VerticalDotsIcon = VerticalDots;
export const LogoWhatsAppIcon = LogoWhatsapp;
export const SeparatorIcon = Separator;
export const PencilIcon = Pencil;
export const PaperClipIcon = PaperClip;
export const DangerIcon = Danger;
export const WhatsAppIcon = WhatsApp;
export const RadioTrueIcon = TrueIcon;
export const RadioFalseIcon = FalseIcon;
export const CheckBoxUncheckIcon = CheckBoxUncheck;
export const CheckBoxIcon = CheckBox;
export const PickupOrderIcon = PickupOrder;
export const CarryingLoadIcon = CarryingLoad;
export const InRouteIcon = InRoute;
export const ArrivalAtDestinationIcon = ArrivalAtDestination;
export const SendingReceiptsIcon = SendingReceipts;
export const BalanceIcon = Balance;
export const BackIcon = Back;
export const PencilSolidIcon = PencilSolid;
export const DownloadIcon = Download;
export const FretadorIcon = Fretador;
export const AttachmentDarkIcon = AttachmentDark;
export const AttachmentLightIcon = AttachmentLight;
export const CloseIcon = Close;
export const CalculatorIcon = FaCalculator;
export const Playicon = Play;
