import { Photo } from "./Photo";
import { Vehicle } from "./Vehicle";
import { VehicleOwner } from "./VehicleOwner";
import { Wallet } from "./Wallet";
import { DriverStatus } from "./Enums";
import { StatusHistoryItem } from "./StatusHistory";
import { RequestedFreightItem } from "./RequestedFreightItem";

export interface Driver {
	_id: string;
	active: boolean;
	cnhPhoto: Photo;
	cnh: string;
	cpf: string;
	creationDate: string;
	updateDate: string;
	id: string;
	name: string;
	password: string;
	rgPhoto: Photo;
	phoneNumber: string;
	phoneNumberSecondary: string;
	proofResidencePhoto: Photo;
	requestedFreights: RequestedFreightItem[];
	status: DriverStatus;
	notificationToken: string[];
	statusHistory: StatusHistoryItem[];
	userPhoto: Photo;
	vehicle: Vehicle;
	wallet: Wallet;
	validated: boolean;
	acknowledge: boolean;
	updateAcknowledge: boolean;
	hashPassword: string;
	invoiceCouponPhotos: Photo[];
	invoicePhoto: Photo;
	pickupOrderPhoto: Photo;
	favoriteFreights: string[];
	city: string;
	state: string;
	email?: string;
	attachments: {
    userPhoto?: string;
		cnh?: string;
		proofResidencePhoto?: string;
		rg?: string;
		vehiclePhoto?: string;
		anttPhoto?: string;
		documentPhoto?: string;
	};
  vehicleOwner?: VehicleOwner;
	isDriverAsOwner?: boolean;
	owner?: VehicleOwner;
}
