export enum PhotoStatus {
	WAITING = "WAITING",
	APPROVED = "APPROVED",
	DENIED = "DENIED",
	ALTERED = "ALTERED",
}

export enum UserStatus {
	WAITING = "WAITING",
	PENDING = "PENDING",
	APPROVED = "APPROVED",
	DENIED = "DENIED",
}

export enum VehicleType {
	THREE_QUARTER = "THREE_QUARTER",
	LIGHT_COMMERCIAL = "LIGHT_COMMERCIAL",
	TOCO = "TOCO",
	VLC = "VLC",
	TRUCK = "TRUCK",
	BI_TRUCK = "BI_TRUCK",
	BI_TREM = "BI_TREM",
	CARRETA = "CARRETA",
	CARRETA_LS = "CARRETA_LS",
	RODOTREM = "RODOTREM",
	VANDERLEIA = "VANDERLEIA",
}

export enum BoardType {
	BAU = "BAU",
	BAU_FRIGORIFICO = "BAU_FRIGORIFICO",
	BAU_REFRIGERADO = "BAU_REFRIGERADO",
	CACAMBA = "CACAMBA",
	GRADE_BAIXA = "GRADE_BAIXA",
	GRANELEIRO = "GRANELEIRO",
	PLATAFORMA = "PLATAFORMA",
	PRANCHA = "PRANCHA",
	APENAS_CAVALO = "APENAS_CAVALO",
	PORTA_CONTAINER = "PORTA_CONTAINER",
	CAVAQUEIRA = "CAVAQUEIRA",
	CEGONHEIRO = "CEGONHEIRO",
	GAIOLA = "GAIOLA",
	HOPPER = "HOPPER",
	MUNCK = "MUNCK",
	SILO = "SILO",
	TANQUE = "TANQUE",
}

export enum AccountType {
	PAMCARD = "PAMCARD",
	CONTA = "CONTA",
}

export enum BoardUserProfile {
	ADMINISTRADOR = "ADMINISTRADOR",
	OPERACAO = "OPERAÇÃO",
	FINANCEIRO = "FINANCEIRO",
	SAC = "SAC",
}