export enum BodyworkCategory {
  ABERTA = "ABERTA",
  FECHADA = "FECHADA",
  ESPECIAL = "ESPECIAL",
}

export enum BodyworkType {
  GRADE_BAIXA = "GRADE_BAIXA",
  GRADE_ALTA = "GRADE_ALTA",
  CARROCERIA = "CARROCERIA",
  PLATAFORMA = "PLATAFORMA",
  BAU = "BAU",
  BAU_FRIGORIFICO = "BAU_FRIGORIFICO",
  SIDER = "SIDER",
  CACAMBA = "CACAMBA",
  TANQUE = "TANQUE",
  GRANELEIRO = "GRANELEIRO",
  MUNCK = "MUNCK",
}
