export enum CargoType {
<<<<<<< HEAD
  ANIMAIS = "ANIMAIS",
  BIG_BAG = "BIG_BAG",
  CAIXAS = "CAIXAS",
  CONTAINER = "CONTAINER",
  DIVERSOS = "DIVERSOS",
  FARDOS = "FARDOS",
  FRACIONADA = "FRACIONADA",
  GRANEL = "GRANEL",
  METRO_CUBICO = "METRO_CUBICO",
  MILHEIRO = "MILHEIRO",
  MUDANCA = "MUDANCA",
  PALETES = "PALETES",
  PASSAGEIRO = "PASSAGEIRO",
  SACOS = "SACOS",
  TAMBOR = "TAMBOR",
  UNIDADES = "UNIDADES",
=======
  ANIMAIS = "Animais",
  BIG_BAG = "Big Bag",
  CAIXAS = "Caixas",
  CONTAINER = "Container",
  DIVERSOS = "Diversos",
  FARDOS = "Fardos",
  FRACIONADA = "Fracionada",
  GRANEL = "Granel",
  METRO_CUBICO = "Metro Cúbico",
  MILHEIRO = "Milheiro",
  MUDANCA = "Mudança",
  PALETES = "Paletes",
  PASSAGEIRO = "Passageiro",
  SACOS = "Sacos",
  TAMBOR = "Tambor",
  UNIDADES = "Unidades",
>>>>>>> 9e03281 (feat(CreateFreight): added enums and update types)
}
