export enum DriverDocumentFieldEnum {
	USER_PHOTO = "USER_PHOTO",
	CNH_PHOTO = "CNH_PHOTO",
	RG_PHOTO = "RG_PHOTO",
	PROOF_RESIDENCE = "PROOF_RESIDENCE",
	VEHICLE_DOCUMENT = "VEHICLE_DOCUMENT",
	VEHICLE_PHOTO = "VEHICLE_PHOTO",
	ANTT_PHOTO = "ANTT_PHOTO",
}
