export enum OccurrenceType {
	TECHNICAL = "TECHNICAL",
	ADMINISTRATIVE = "ADMINISTRATIVE",
	OTHERS = "OTHERS",
	COMPLAINT = "COMPLAINT",
	COMPLIMENT = "COMPLIMENT",
	FREIGHT_CANCELLATION = "FREIGHT_CANCELLATION",
	SCHEDULE_CHANGE = "SCHEDULE_CHANGE",
	GENERAL_CHANGES = "GENERAL_CHANGES",
	VEHICLE_PROBLEM = "VEHICLE_PROBLEM",
	ROUTE_PROBLEM = "ROUTE_PROBLEM",
	ROUTE_CHANGE = "ROUTE_CHANGE",
}
